Fails due to missing NRT annotations
System\Windows\Forms\Cursor.cs(530,30): error RS0036: Symbol 'Equals' is missing nullability annotations in the declared API. [C:\Development\!Repro\2778\src\System.Windows.Forms\src\System.Windows.Forms.csproj]