Update the analyzer
Fails with
System\Windows\Forms\Cursor.cs(530,30): error RS0037: PublicAPI.txt is missing '#nullable enable', so the nullability annotations of API isn't recorded. It is recommended to enable this tracking. [C:\Development\!Repro\2778\src\System.Windows.Forms\src\System.Windows.Forms.csproj]